/**
 * Personal + Business taxonomies for the transaction drawer's
 * Booked Attribution section. Each top-level bucket has a label,
 * a tax-treatment hint (business only), and a list of sub-categories.
 *
 * The lists are intentionally pragmatic — covering the real categories
 * a multi-entity holding company (Bytes AI + Rocket Wireless +
 * Delicious Bytes + Amari Muharram Holdings) actually deals with on
 * Chase imports, plus the typical personal expense buckets.
 */

export interface CategoryBucket {
  label: string;
  tax?: string;
  subs: string[];
}

export const PERSONAL_CATEGORIES: Record<string, CategoryBucket> = {
  HOUSING: {
    label: 'Housing',
    subs: [
      'Monthly rent',
      'Mortgage — principal & interest',
      'Mortgage — escrow / taxes & insurance',
      'Home insurance',
      'Property tax',
      'HOA / condo fees',
      'Home repairs & maintenance',
      'Utilities — electric',
      'Utilities — gas',
      'Utilities — water & sewer',
      'Utilities — internet & cable',
      'Utilities — trash & recycling',
      'Furniture & decor',
      'Appliances',
      'Lawn & landscaping',
      'Cleaning service',
      'Pest control',
      'Home security',
    ],
  },
  FAMILY: {
    label: 'Family & Personal Care',
    subs: [
      'Family support — parents',
      'Family support — siblings',
      'Family support — children',
      'Spousal support',
      'Child care / daycare',
      'School tuition',
      'After-school activities',
      'Tutoring',
      'Clothing — self',
      'Clothing — family',
      'Salon / barber',
      'Personal care & toiletries',
      'Gifts given',
      'Charitable giving',
      'Zakat',
      'Religious obligation — Hajj / Umrah',
      'Mosque / community',
      'Pets — food',
      'Pets — vet',
      'Pets — supplies & grooming',
    ],
  },
  FOOD: {
    label: 'Food & Dining',
    subs: [
      'Grocery store',
      'Halal grocery / butcher',
      'Farmers market',
      'Restaurant — casual',
      'Restaurant — fine dining',
      'Restaurant — fast food',
      'Coffee shop',
      'Food delivery (personal)',
      'Bars & alcohol',
      'Specialty / bakery',
    ],
  },
  TRANSPORT: {
    label: 'Transportation',
    subs: [
      'Gas & fuel',
      'Car payment',
      'Car lease',
      'Auto insurance',
      'Auto repair & maintenance',
      'Vehicle registration / DMV',
      'Parking',
      'Tolls',
      'Rideshare — Uber',
      'Rideshare — Lyft',
      'Taxi',
      'Public transit',
      'Flights (personal)',
      'Car wash & detailing',
      'EV charging',
    ],
  },
  HEALTH: {
    label: 'Health & Wellness',
    subs: [
      'Primary care visit',
      'Specialist visit',
      'Dental',
      'Vision / glasses / contacts',
      'Pharmacy / prescriptions',
      'Health insurance premium',
      'HSA / FSA contribution',
      'Mental health / therapy',
      'Gym & fitness',
      'Yoga / pilates / studio',
      'Supplements & vitamins',
      'Personal trainer',
      'Medical equipment',
      'Lab / imaging',
    ],
  },
  ENTERTAINMENT: {
    label: 'Entertainment',
    subs: [
      'Streaming — Netflix',
      'Streaming — Spotify / Apple Music',
      'Streaming — other (Hulu, Disney+, etc.)',
      'Gaming',
      'Books / Kindle / Audible',
      'Events / concerts / shows',
      'Sports tickets',
      'Vacation — flights',
      'Vacation — hotels',
      'Vacation — activities & tours',
      'Hobbies & crafts',
      'Magazines / news subscriptions',
    ],
  },
  SAVINGS: {
    label: 'Savings & Finance',
    subs: [
      'Emergency fund transfer',
      'Retirement — 401k',
      'Retirement — IRA / Roth',
      'Brokerage / investment',
      'Credit card payment',
      'Student loan payment',
      'Personal loan payment',
      'Bank fees (personal)',
      'Wire / transfer fees',
      'Investment management fees',
      'Crypto purchase',
      '529 college savings',
    ],
  },
  OWNER: {
    label: 'Owner Draws',
    subs: [
      'Monthly distribution',
      'Salary draw',
      'Bonus draw',
      'Profit share — personal',
      'Reimbursement to self',
      'Tax distribution',
    ],
  },
};

export const BUSINESS_CATEGORIES: Record<string, CategoryBucket> = {
  COGS: {
    label: 'Cost of Goods Sold',
    tax: '100% deductible',
    subs: [
      'Wireless inventory (SIMs, devices)',
      'Food ingredients & raw materials',
      'Packaging & containers',
      'Delivery platform commission (DoorDash, Grubhub, Uber Eats)',
      'Marketplace fees (Amazon, etc.)',
      'Fulfillment / 3PL',
      'Direct kitchen labor',
      'Freight & inbound shipping',
      'Shrinkage / spoilage / waste',
      'Returns & refunds',
    ],
  },
  PAYROLL: {
    label: 'Payroll & Compensation',
    tax: '100% deductible — wages',
    subs: [
      'Salary — W-2',
      'Hourly wages — W-2',
      'Contractor payment — 1099',
      'Owner salary',
      'Bonus / commission',
      'Payroll tax — employer side',
      'Health benefits (premiums)',
      'Dental & vision benefits',
      'Retirement match — 401k',
      'Workers comp insurance',
      'PTO / sick payout',
      'Severance',
      'Employee reimbursement',
      'Stipends (phone, internet, wellness)',
      'Payroll service fees (Gusto, Rippling, etc.)',
    ],
  },
  SOFTWARE: {
    label: 'Software & Technology',
    tax: '100% deductible',
    subs: [
      'AI / ML APIs (Anthropic, OpenAI)',
      'Cloud infrastructure (AWS, GCP, Vercel)',
      'Voice & telephony (Twilio, Plivo)',
      'Database / data warehouse',
      'Product tools (Figma, Linear, Notion)',
      'Analytics (Mixpanel, Amplitude, PostHog)',
      'Dev tools (GitHub, Cursor, IDEs)',
      'Email & messaging (Slack, Google Workspace)',
      'CRM & sales (HubSpot, Salesforce)',
      'Customer support (Intercom, Zendesk)',
      'Security & monitoring',
      'Domain & DNS',
      'SaaS subscriptions — other',
    ],
  },
  MARKETING: {
    label: 'Marketing & Sales',
    tax: '100% deductible',
    subs: [
      'Paid ads — Meta (Facebook / Instagram)',
      'Paid ads — Google',
      'Paid ads — TikTok',
      'Paid ads — other channels',
      'Content & creative production',
      'SEO / website',
      'Influencer marketing',
      'PR & press',
      'Events / sponsorships',
      'Trade shows',
      'Branding & design',
      'Referral program payouts',
      'Affiliate payouts',
      'Sales tools & enablement',
    ],
  },
  RENT: {
    label: 'Rent & Facilities',
    tax: '100% deductible',
    subs: [
      'Office rent',
      'Ghost kitchen rent',
      'Coworking',
      'Warehouse / storage',
      'Equipment lease',
      'Utilities — electric',
      'Utilities — gas',
      'Utilities — water & sewer',
      'Utilities — internet & phone',
      'Janitorial / cleaning',
      'Maintenance & repairs',
      'Property / liability insurance',
      'Security & alarm',
      'Commercial property tax',
    ],
  },
  PRO: {
    label: 'Professional Services',
    tax: '100% deductible',
    subs: [
      'Legal',
      'Accounting / CPA',
      'Bookkeeping',
      'Tax preparation',
      'Consulting',
      'Recruiting & staffing agency',
      'IT / managed services',
      'Business licenses & permits',
      'Notary & certifications',
      'Insurance broker',
      'Compliance & audit',
    ],
  },
  BANKING: {
    label: 'Banking & Finance',
    tax: '100% deductible',
    subs: [
      'Bank fees / service charges',
      'Wire fees',
      'ACH fees',
      'FX fees',
      'NSF / overdraft fees',
      'Merchant processing (Stripe, Square)',
      'Credit card processing',
      'Loan interest',
      'Credit card interest',
      'Line of credit interest',
      'SBA loan payment',
      'Investment management fees',
    ],
  },
  TRAVEL: {
    label: 'Travel & Entertainment',
    tax: '50–100% deductible',
    subs: [
      'Business flights',
      'Hotels',
      'Ground transport (Uber, taxi)',
      'Rental car',
      'Mileage reimbursement',
      'Per diem',
      'Client meals (50%)',
      'Team meals (100%)',
      'Conferences & registration',
      'Industry events',
      'Client entertainment',
      'Travel insurance',
    ],
  },
  TAX: {
    label: 'Taxes',
    tax: 'Not deductible (income tax)',
    subs: [
      'Federal income tax — entity',
      'State income tax — entity',
      'Local / city tax',
      'Estimated quarterly tax',
      'Payroll tax remittance',
      'Sales tax remittance',
      'Franchise tax / annual report',
      'Property tax — commercial',
      'Foreign tax',
      'Tax penalties & interest',
    ],
  },
  INTERCO: {
    label: 'Inter-Entity',
    tax: 'Track separately — not P&L',
    subs: [
      'Loan to related entity',
      'Loan repayment from related entity',
      'Management fee',
      'Capital contribution to subsidiary',
      'Distribution / dividend out',
      'Distribution to owner (Amari Muharram Holdings)',
      'Reimbursement between entities',
      'Allocated shared expense',
      'Intercompany transfer',
    ],
  },
  CAPEX: {
    label: 'Capital Expenditure',
    tax: 'Depreciate / amortize',
    subs: [
      'Computer & hardware',
      'Office equipment',
      'Furniture & fixtures',
      'Kitchen equipment',
      'Vehicles',
      'Leasehold improvements',
      'Software (capitalized)',
      'Patents / trademarks',
      'Real estate purchase',
      'Major renovations',
    ],
  },
  OTHER: {
    label: 'Other Business',
    tax: 'Review case-by-case',
    subs: [
      'General liability insurance',
      'Cyber / errors & omissions insurance',
      'Directors & Officers (D&O)',
      'Office supplies',
      'Postage & shipping',
      'Subscriptions — misc',
      'Charitable donations (business)',
      'Penalties & fines',
      'Bad debt write-off',
      'Foreign exchange loss / gain',
      'Membership dues',
      'Settlement payment',
    ],
  },
};

/** Inflow categories for business inflows (Stripe payouts, marketplace
 *  payouts, investor wires, etc.). Used when transaction.amount > 0 and
 *  Booked Attribution is on the Business path. */
export const BUSINESS_INCOME_CATEGORIES: Record<string, CategoryBucket> = {
  SAAS: {
    label: 'SaaS Revenue',
    tax: 'Ordinary revenue',
    subs: [
      'Subscription revenue',
      'Usage-based revenue',
      'Setup / onboarding fee',
      'Upgrade / expansion',
      'Renewal',
      'Stripe payout',
    ],
  },
  MARKETPLACE: {
    label: 'Marketplace Revenue',
    tax: 'Ordinary revenue',
    subs: [
      'DoorDash payout',
      'Grubhub payout',
      'Uber Eats payout',
      'Amazon settlement',
      'Other marketplace settlement',
    ],
  },
  WIRELESS: {
    label: 'Wireless / TCETRA Revenue',
    tax: 'Ordinary revenue',
    subs: [
      'TCETRA settlement',
      'Wireless activation',
      'Renewal / top-up',
      'Inventory rebate',
      'Carrier commission',
    ],
  },
  SERVICES: {
    label: 'Services / Consulting',
    tax: 'Ordinary revenue',
    subs: [
      'Consulting fee',
      'Implementation fee',
      'Retainer',
      'Hourly billing',
      'One-off project',
    ],
  },
  CAPITAL: {
    label: 'Capital Investment',
    tax: 'Not income — equity / debt',
    subs: [
      'Founder contribution',
      'Investor wire — equity',
      'SAFE note',
      'Convertible note',
      'Equity round',
      'Tranche call',
    ],
  },
  LOAN: {
    label: 'Loan Proceeds',
    tax: 'Not income — liability',
    subs: [
      'SBA loan disbursement',
      'Line of credit draw',
      'Personal loan to business',
      'Vendor financing',
      'Merchant cash advance',
    ],
  },
  REFUND: {
    label: 'Refund / Rebate',
    tax: 'Offset to original expense',
    subs: [
      'Vendor refund',
      'Tax refund',
      'Insurance refund / payout',
      'Marketplace rebate',
      'Chargeback returned',
    ],
  },
  INTEREST: {
    label: 'Interest & Investment Income',
    tax: 'Ordinary income',
    subs: [
      'Bank interest',
      'Money market / treasuries',
      'Brokerage dividend',
      'Realized gain',
    ],
  },
  INTERCO_IN: {
    label: 'Inter-Entity Inflow',
    tax: 'Track separately — not P&L',
    subs: [
      'Loan repayment from related entity',
      'Capital contribution from sibling',
      'Distribution received',
      'Management fee in',
      'Reimbursement from sibling',
      'Intercompany transfer in',
    ],
  },
  OTHER_IN: {
    label: 'Other Income',
    tax: 'Review case-by-case',
    subs: [
      'Grant / award',
      'Settlement received',
      'Foreign exchange gain',
      'Asset sale proceeds',
      'Miscellaneous',
    ],
  },
};

/** Personal inflow categories — salary deposits, distributions you take
 *  from your own businesses, gifts, refunds, etc. */
export const PERSONAL_INCOME_CATEGORIES: Record<string, CategoryBucket> = {
  EARNED: {
    label: 'Earned Income',
    subs: [
      'Salary / wages — W-2',
      'Contractor income — 1099',
      'Bonus / commission',
      'Tip income',
    ],
  },
  OWNER_DRAW: {
    label: 'Owner Draws / Distributions',
    subs: [
      'Distribution — Bytes AI',
      'Distribution — Rocket Wireless',
      'Distribution — Delicious Bytes',
      'Distribution — Amari Ventures',
      'Distribution — Amari Muharram Holdings',
      'Profit share',
      'Tax distribution',
    ],
  },
  INVESTMENT_IN: {
    label: 'Investment Returns',
    subs: [
      'Brokerage dividend',
      'Realized gain',
      'Crypto sale',
      'Real estate income',
    ],
  },
  REFUND_IN: {
    label: 'Refund / Rebate',
    subs: [
      'Vendor refund',
      'Tax refund',
      'Insurance refund',
      'Chargeback returned',
    ],
  },
  GIFT: {
    label: 'Gift / Transfer Received',
    subs: [
      'Gift from family',
      'Gift from friend',
      'Inheritance',
      'Transfer between own accounts',
    ],
  },
  OTHER_IN: {
    label: 'Other Personal Income',
    subs: [
      'Miscellaneous',
      'Cash deposit',
    ],
  },
};
